# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "weekly"
      time: "04:00"
      # timezone: "Europe/Kyiv"

    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "npm"

    labels:
      - "npm dependencies"

    reviewers:
      - "Alexander Yukal"
